### ISSUE TITLE
MutationObserver

### ISSUE THREAD

**Issue by sminnee** [litejs/dom#23]
@bnolan and I are looking to build a MutationObserver to work with dom-lite, a la the Mozilla API: https://developer.mozilla.org/en/docs/Web/API/MutationObserver

Is this something that you would be interested in for the main project? It won't be possible without modifications dom-lite itself and we'd rather not maintain a fork, but perhaps the bulk of the MutationObserver can be kept outside of dom-lite, and we can just add some event hooks for the relevant dom-lite calls.

Is this a PR you'd be likely to accept?

**Comment by lauriro** [comment]
I think that modifications in dom-lite for outside implementation would be in similar size as implementation in dom-lite itself.

This can be part of main project, feel free to send PR with tests.

**Comment by sminnee** [comment]
Thanks, @lauriro I'll let you know when I have a tested version. I'd expect it'll be a couple of weeks.

**Comment by bnolan** [comment]
I'm not sure why this has been closed. 60 weeks is still clearly a "couple of weeks".

;)

https://github.com/litejs/dom-lite/compare/master...scenevr:master

**Comment by bnolan** [comment]
I need to write some tests for it, and get rid of the lodash-debounce dependency and then I think it'd be good to go. There is some performance overhead if you are not using mutation observers, so I'd like to think of a way to mitigate that (eg make`dispatchMutation` a no-op unless you have registered an observer) - but it was super duper easy to do, and help towards my master plan. Mwuhahaha.

**Comment by bnolan** [comment]
I guess I should take a look at the [DOM Spec](https://www.w3.org/TR/dom/#mutation-observers) too and see if it's doing things right, but currently I'm gonna tag that with [cbf](http://www.urbandictionary.com/define.php?term=cbf).

**Comment by lauriro** [comment]
Issues can be always reopened, for a moment this one felt forgotten.
Check also coding style from readme (Use tabs for indentation).

**Comment by bnolan** [comment]
Okay I've done some more work on this and it's working pretty well. I don't have support for `characterData`, but I'll let you know when it's ready for review. :)
